Scrivito/scrivito_example_app_js

src/Components/AuthorImage.js
src/Components/BlogPost/BlogPostAuthor.js
src/Objs/Author/AuthorComponent.js
src/Objs/Author/AuthorEditingConfig.js
src/Objs/Event/EventEditingConfig.js
src/Objs/Job/JobEditingConfig.js
src/Widgets/AddressWidget/AddressWidgetEditingConfig.js
src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
src/Widgets/TextWidget/TextWidgetEditingConfig.js

Scrivito is not yet fully ready to support editing a html or string attribute "in place" and on the widget/page properties. So to avoid confusion one attribute can now only be edited "in place" XOR on the widget/page properties.

Edit attribute only inplace XOR in widget/page properties

---

package-lock.json
package.json

Version 0.5.15 and 0.5.16 do not work with the prerenderer of Netlify. Fixes #3.
> npm install --save-dev react-images@0.5.14
Prove: `curl -A twitterbot https://5a71b243efbe5d6f4c9722e6--scrivito-example.netlify.com/` (Preview deploy URL of netlify).
Bonus: This reduces the payload of `index.js` by ~100 kb! Next time I do npm package update I'll have a closer look on the resulting size.

Downgraded react-images to 0.5.14.

---

src/Widgets/ImageWidget/ImageWidgetClass.js
src/Widgets/ImageWidget/ImageWidgetComponent.js
src/Widgets/ImageWidget/ImageWidgetEditingConfig.js

Adds a new *Link* option to `ImageWidget`:
If set, the image will be a link to the given page/external URL. If in edit mode, clicking on the image opens the content browser regardless of a link set or not.

ImageWidget: Added optional "link" attribute.

---

src/Globals.js
src/index.js

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/5128#issuecomment-131638288 for an explanation
There are other imports that currently don't work out of the box for the same reason (e.g. all `lodash/xyz`), but changing these will make the imports look silly, so it's better to use `allowSyntheticDefaultImports` in a TS environment.

TypeScript compatible React imports

---

src/Components/AuthorImage.js

If the editor selects something else than an image, it currently results in an empty "space". This is replaced with a hint to the editor.

author image component: no image selected

---

src/Objs/_defaultPageEditingConfig.js
src/Widgets/HeadlineWidget/HeadlineWidgetComponent.js
src/Widgets/HeadlineWidget/HeadlineWidgetEditingConfig.js

Solves: https://trello.com/c/mJeVxUWv/292-initialcontent-for-pages-do-have-a-headline-with-h1-initialcontent-of-headlines-are-h2

headline widget: default style and tag should be h2

---

package-lock.json
package.json

Output of command:
```
+ async@2.6.0
+ convert-source-map@1.5.1
+ crypto-browserify@3.12.0
+ domain-browser@1.2.0
+ electron-to-chromium@1.3.33
+ ajv-keywords@2.1.1
+ ajv@5.5.2
+ caniuse-lite@1.0.30000804
+ acorn@5.4.1
+ commander@2.14.1
+ errno@0.1.6
+ es-abstract@1.10.0
+ es5-ext@0.10.38
+ http-parser-js@0.4.10
+ interpret@1.1.0
+ js-base64@2.4.3
+ inquirer@3.3.0
+ highlight-words-core@1.1.2
+ lodash.mergewith@4.6.1
+ make-dir@1.1.0
+ mime-db@1.32.0
+ regenerator-runtime@0.11.1
+ mississippi@1.3.1
+ multicast-dns@6.2.3
+ nan@2.8.0
+ object.assign@4.1.0
+ promise-polyfill@7.1.0
+ p-limit@1.2.0
+ selfsigned@1.10.2
+ request@2.83.0
+ semver@5.5.0
+ ssri@5.2.1
+ ua-parser-js@0.7.17
+ stream-http@2.8.0
+ statuses@1.4.0
+ uuid@3.2.1
+ webpack-sources@1.1.0
added 35 packages, removed 7 …
```

npm update --depth 9999

---

src/Components/ErrorBoundary.js
src/Components/NotFoundErrorPage.js
src/utils/getMetaData.js

https://prerender.io/documentation/best-practices recommends, that a `prerender-status-code` `meta` tag will be rendered with the resulting status code.
* For regular pages status code `200` is reported.
* For not found pages status code `404` is reported.
* For the error boundary (aka internal error page)  status code `500` is reported.
`
curl -v -A twitterbot https://deploy-preview-29--scrivito-example.netlify.com` reports `HTTP/2 200`.
`curl -v -A twitterbot https://deploy-preview-29--scrivito-example.netlify.com/doesnotexit` reports `HTTP/2 404`.
Previously not found error pages reported `HTTP/2 200`. Try it out with `curl -v -A twitterbot https://scrivito-example.netlify.com/doesnotexit`.

Prerender.io - correct status codes

---

src/Components/CurrentPageMetaData.js

This PR includes the canonical tag for every page to the HTML head section.  `<link rel='canonical' href="https://my-website-url/my-canonical-page-path" />`. 
The canonical tag is important for SEO reasons to prevent the penalizing for duplicate content on the website from google. For further reading see: https://support.google.com/webmasters/answer/139066

Add the canonical url of the current page to the HTML head section

---

public/_headers

Allow the client verification via https://api.scrivito.com/javascripts/verification/hashcash.js

Support Scrivito rate limit client verification

---

src/Components/Navigation/NavigationSection.js
src/assets/stylesheets/index.scss

Allow medium sized headers to show the widget list.
@agessler can you pls have a look if the design is good or what we can do to change the padding?

show widget section for medium sized headers

---

src/Objs/BlogPost/BlogPostEditingConfig.js

The old description can be confused with a "valid from" date.

Less misleading description for publish date

---

package-lock.json
package.json
src/Components/BlogPost/BlogPostPreviewList.js
src/Components/SchemaDotOrg.js
src/Components/SchemaDotOrg/dataFromBlogPost.js
src/Components/ScrivitoExtensions/ColumnsEditorTab.js
src/Components/ScrivitoExtensions/IconEditorTab/AllIcons.js
src/Objs/SearchResults/SearchResultItem.js
src/Widgets/TestimonialWidget/TestimonialWidgetEditingConfig.js
src/utils/getMetaData.js

"lodash-es" supports tree shaking of webpack. So no more partial imports needed for lodash!
The filesize remains more or less the same.

Use "lodash-es" instead of "lodash".

---

package-lock.json
package.json

* According to https://github.com/webpack/webpack/issues/520#issuecomment-331689542, all deps should reside in `dependencies`
* This also improves compatibility with the default behavior of `npm install x`
There is some debate about where dependencies go. IMO a good rationale is the summary of https://github.com/webpack/webpack/issues/520#issuecomment-331689542:
> Webpack projects should be considered build-type projects first, and not production-type projects, unless webpack is used in production. Packages needed during production goes in `dependencies`, and packages used just to develop the project goes in `devDependencies`. If our production environment needs to build (run webpack), then those dependencies must reside in `dependencies`.

Package dev dependencies are now dependencies

---

package-lock.json
package.json
webpack.config.js

Webpack has an build-in plugin to handle `process.env` variables https://webpack.js.org/plugins/environment-plugin/#usage-with-default-values . In my opinion this is a good documented way and makes the `inline-environment-variables-webpack-plugin` obsolete. 
So this PR updates the `webpack.config.js` to use the build-in plugin and removes the `inline-environment-variables-webpack-plugin` from the package.json.

use the webpack build-in plugin to handle env variables

---

src/Objs/SearchResults/SearchInput.js

This change fixes 2 potential issues:
1. An undefined value may trigger a controlled/uncontrolled console warning.
2. The implementation of `getDerivedStateFromProps` may revert user input on updates. AFAICS it's not needed at all.

Fix issues of SearchInput

---

package-lock.json
package.json
webpack.config.js

With the current setup a production build may suffer from issues of `uglify-es`, which is no longer maintained.
https://github.com/webpack-contrib/terser-webpack-plugin uses Terser, which is more up-to-date, and replaces uglify-es.
Sorry for typos 😜

Minimize build with Terser

---

src/assets/stylesheets/index.scss

https://trello.com/c/QkmEwbJn/340-navigation-on-mobile-for-pages-without-path-look-different
`navbar-nav` object inherits text-align from `medium-height` element, added specific `text-align` value for links in the nav

Changed text-align of links in nav

---

src/Components/BlogPost/BlogPostTagList.js
src/assets/stylesheets/index.scss

https://trello.com/c/oJ0X0umU/348-tag-list-under-a-blog-post-looks-broken-if-there-are-more-than-one-tag
Added new class `margin-right` and used it for tags under blog post

Added margin to tags under a blog post

---

package-lock.json
package.json
webpack.config.js

Use the latest version of `striptags`. It needs to be compiled by babel, but should *not* be enriched with polyfills, since that will break webpack with the following message:
```
"export 'default' (imported as 'striptags') was not found in 'striptags'
@ ./utils/textExtract.js
@ ./Objs/SearchResults/SearchResultItem.js
@ ./Objs sync \.js$
@ ./Objs/index.js
@ ./sitemap.js
```
Thanks to the [`overrides`](https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages#selective-compilation-with-overrides) option it is possible to disable the given `@babel/preset-env` rule.

Striptags 3

---

extend-csp-headers-webpack-plugin.js
public/_headers

It is now up to `_headers` to decide how the header should be named. With that it should be easier to change `Content-Security-Policy` to `Content-Security-Policy-Report-Only`.
Follow-up of https://github.com/Scrivito/scrivito_example_app_js/pull/97.

Better CSP Placeholder

---

src/Objs/Redirect/RedirectComponent.js

Redirects an internal link a more soft way, keeping the single page app loaded.
How to check:
Open Example App in UI
Switch to Editing
Open ContentBrowser
Search `Redirect`
Select first Page `Redirect` (remember its `id`, if necessary).
Switch off `openInUi`
Finally: provide a `hash` to the link (beyond capabilities of current UI)
```
// enter application frame first
Scrivito.load(() => Scrivito.getClass('Redirect').all().take(1));
obj = Scrivito.getClass('Redirect').all().take(1)[0];
newLink = obj.get('link').copy({ hash: 'gohere' }):
obj.update({ link: newLink });
```
Then click `/scrivito` on the homepage and see the `#gohere` be appended to the address bar.

Use navigateTo for internal links

---

src/Components/BlogPost/BlogPostNavigation.js
src/Components/Navigation/Search.js

https://trello.com/c/G50MIOcA/384-replace-take1-with-first
Changed method `take(1)` on `first()` according to new scrivito version (1.3.0).
See documentation for `first()` method -> https://www.scrivito.com/js-sdk/ObjSearch-first

Changed take(1) on first()

---

AddSitemapToRedirectsWebpackPlugin.js
ExtendCspHeadersWebpackPlugin.js

Since the introduction of `ExtendCspHeadersWebpackPlugin` `npm start` blocks on auto recompile.
This PR does two thinks:
* Switch from `tapAsync` to `tapPromise` because it helps better to surface errors.
* Skip `ExtendCspHeadersWebpackPlugin` if `_headers` or `_headersCsp.json` is missing. This is for example the case during a auto recompile, when running `webpack-dev-server`.

Bugfix: Autoreloading works again

---

src/Components/Navigation.js

https://trello.com/c/J3WAVqpV/372-design-check-use-new-options-of-scrivitobackgroundimagetag-eg-position
This PR adds position bottom to the `useGradient` mode in navigation.

Extended usegradiant mode in navigation by adding position

---

public/_headersCsp.json

"unsafe-inline" is needed for style-src, so that for example animations of `react-reveal` can work. Also our BackgroundImageTag AFAIK does use inline styles.
This gives us a `A+` rating on securityheaders.com:

CSP: No more "unsafe-inline" for default. Instead only us it for style-src

---

src/Objs/Redirect/RedirectComponent.js
src/Objs/Redirect/RedirectEditingConfig.js
src/Objs/Redirect/RedirectObjClass.js

This PR reverts https://github.com/Scrivito/scrivito_example_app_js/pull/105. `Scrivito.navigateTo` is not good enough in this case, because it does do a browser location push instead of a replace. This means, that a "navigate back click" does bring you back to the redirect obj, which then will redirect you again - quite annoying and also noticed by our customers.
This PR also includes two improvements for Redirect Objs:
* ~~When in edit mode the redirect does not take place. This allows the editor to change page properties of a redirect without having to go to the Content Browser.~~ **EDIT**: Did remove the functionality for now.
* A redirect obj now also has a title. This is useful, if someone includes the redirect obj in the navigation. Then it should be possible to edit the title.

Redirect obj bugfix

---

generator-scrivito/generators/obj/index.js
generator-scrivito/generators/widget/index.js

According Andreas feedback this PR's changing order of calling render methods.
**Order consistent with documentation:**
`create src/Widgets/TitleWidget/TitleWidgetClass.js`
`create src/Widgets/TitleWidget/TitleWidgetEditingConfig.js`
`create src/Widgets/TitleWidget/TitleWidgetComponent.js`

Yeoman generator - changed order of render methods

---

src/Widgets/ImageWidget/ImageWidgetEditingConfig.js

The description for the link attribute in image widget is different now according to Andreas feedback. 
`The link where this image should lead.` -> `The page to open after clicking the image.`

Changed the description for link attribute in the image widget

---

storePrerenderedContent.js

Given the following `rerenderContent`:
```js
function prerenderContent() {
return new Promise(resolve => {
resolve([
{ fileName: "../bad.html", fileContent: "should not be there" },
{ fileName: "/good.html", fileContent: "isFine" },
{ fileName: "/also/good.html", fileContent: "isFineToo" },
{ fileName: "google_analytics.js", fileContent: "OVERWRITE!!" },
]);
});
}
```
The file `bad.html` should not be stored, since it could "escape" the `TARGET_DIR`. Also `google_analytics.js` should not be overwritten, since it already exists in `build/`.
If one of the two cases is detected, it is not stored and a warning is logged. I'm not sure, if we should fail the build, if this happens.

Prerender security

---

src/prerenderContent/prerenderObjs.js

Wished by Andreas.
FYI: `Scrivito.urlFor` is called outside of a `load` context. But at the time of the call `Scrivito.urlFor` should have already all needed data to not complain about incomplete data.

[prerender] Log url of failed obj.

---

.travis.yml
package-lock.json
package.json
webpack.config.js

`es-check` is a validation tool, that checks the transpiled output for valid es5 syntax. With this tool I discovered, that our current `google_analytics.js` is not completely transpiled for older browser.
I discovered this tool thru https://levelup.gitconnected.com/lessons-learned-from-a-year-of-fighting-with-webpack-and-babel-ce3b4b634c46.

npm run es-check

---

src/assets/stylesheets/_pt_sans_narrow.scss
src/assets/stylesheets/_source_sans_pro.scss
src/assets/stylesheets/fontawesome/_path.scss
src/assets/stylesheets/index.scss

While downloading a custom font (e.g. PT Sans Narrow or Source Sans Pro) another system font should be shown.
This improves the "First Meaningful Paint" metric in lighthouse:
See https://css-tricks.com/font-display-masses/ for details on the css flag. Currently Firefox, Chrome and Safari (Mobile) have implemented this feature. Only IE does not support the feature, but will not break if used.

css: Use font-display: swap

---

webpack.config.js

Saves 2.15 k
See https://github.com/webpack-contrib/terser-webpack-plugin#extractcomments
IMO the licence is still distributed with the software, but if you are unsure about legal implications, feel free to close.

Extract comments from bundle

---

src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js

Fixes #173.
Thanks to @capriosa for the report and the bugfix!

Bugfix: Filter tags in ThumbnailGalleryWidget correctly.

---

package-lock.json
package.json
src/prerenderContent/prerenderSitemap.js
webpack.config.js

I just discovered unexpected polyfill code in my bundle. That's how I found out about this option.
Luckily the Example App had only one dependency on a node feature: `stream` used by `sax` used by `xml`.

Reduce bundle size by setting webpack node to false

---

.eslintrc
src/Components/GoogleAnalytics.js
src/Components/Intercom.js
src/Components/Navigation/Logo.js
src/Components/Navigation/currentPageNavigationOptions.js
src/Components/SchemaDotOrg.js
src/Components/ScrivitoExtensions/ColumnsEditorTab.js
src/Components/ScrivitoExtensions/IconEditorTab.js
src/Widgets/BlogOverviewWidget/BlogOverviewWidgetComponent.js
src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js
src/prerenderContent/filenameFromUrl.js
src/utils/textExtract.js

Removed a lot of overwrites of eslint rules.
The only default rules, that are still off are `react/display-name`, `react/prop-types` and `vars-on-top`.

Simpler eslint rules

---

src/Widgets/TickListWidget/TickListWidgetClass.js
src/Widgets/TickListWidget/TickListWidgetComponent.js
src/Widgets/TickListWidget/TickListWidgetStyles.scss
src/Widgets/VimeoVideoWidget/VimeoVideoWidgetComponent.js
src/Widgets/VimeoVideoWidget/VimeoVideoWidgetStyles.scss
src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetComponent.js
src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetStyles.scss
src/assets/stylesheets/index.scss
src/index.js
webpack.config.js

Motivation: This PR sets the base-line to further improve our stylesheets.
Ideally we want a style sheet file per widget/obj, with a base-line `index.scss`. `css-loader` and `MiniCssExtractPlugin` will combine this multiple css files into one big `index.css` file.
As a proof of concept I converted the styling of `TickListWidget`, `VimeoVideoWidget` and `YoutubeVideoWidget` to show, how it is done.

index.css via css-loader

---

src/prerenderContent/generateHtml.js

With the space, a local dev server serving the prerendered content would log this in the browser console:
```
Warning: Did not expect server HTML to contain the text node "
" in <div>.
```

Less warnings with prerendering and dev server

---

src/Objs/Redirect/RedirectComponent.js
src/Objs/Redirect/RedirectEditingConfig.js
src/Objs/Redirect/RedirectObjClass.js
src/Objs/RedirectToUi/RedirectToUiComponent.js
src/Objs/RedirectToUi/RedirectToUiEditingConfig.js
src/Objs/RedirectToUi/RedirectToUiObjClass.js

Prior to this PR there has been only the `Redirect` obj, that surfed two different purposes: Redirect to a link or open a page in the Scrivito UI.
The second part is a very specific task, that we - more or less - only need on the example content on the first "call to action" button, where novice scrivito editors can try out scrivito. Outside of this narrow use-case no other editor would use it.
Other than that it does not add much value. On the contrary: It can even be harmful, if a regular redirect obj receives the "openInUi" tick. This can lead to a "harmless" redirect to break you page, since regular visitors are also redirected to the Scrivito UI.
This PR adds a dedicated `RedirectToUi` obj, that only has the purpose of redirecting to the UI. The regular `Redirect` obj no longer has …

Redirect's openInUi considered harmful

---

src/Components/Navigation/Search.js

The `SearchIcon` accesses `Scrivito.currentPage()`. This call
implicitely loads an `Scrivito.Obj` (unless already loaded).
A flaw in the current SDK doesn't enforce a `connect`, with the
disadvantage that nothing triggers the loading actually. If
`SearchIcon` where used alone, it would always fail to check
the current page's class.
Therefore we better have the example code on the safe and working side.
Note: If `SearchIcon` were used inside a `Scrivito.CurrentPage`, the
`Obj` would have been loaded, and the call to `Scrivito.currentPage()`
would yield a result. Because the SDK doesn't enforce `connect` for
loaded things, this would then "work" as expected.

Connect SearchIcon

---

src/assets/stylesheets/index.scss

During the conversion from bootstrap 3 to 4 this got overlooked.
In "_modal.scss" the ".modal-backdrop" now defines the "z-index" using "$zindex-modal-backdrop"
Found threw `npx find-unused-sass-variables src/assets/stylesheets`

[css] Corrected variable name zindex-modal-backdrop

---

src/index.js

Import index.scss after Obj&Widgets to prevent overwriting styles while importing single scss files (like mixins, fontawesome etc.) into components.

changed import order of index.scss

---

src/Widgets/LinkContainerWidget/LinkContainerWidget.scss
src/Widgets/LinkContainerWidget/LinkContainerWidgetComponent.js
src/assets/stylesheets/index.scss

- chunked LinkContainerWidget styles
- added b-bottom class in JSX instead of extending `.link-container-widget--headline` with it

chunked LinkContainerWidget styles

---

public/_scrivito_extensions.html
public/catch_all_index.html
src/prerenderContent/generateHtml.js

We preconnected via resource hints only to api.scrivito.com - this PR extends it also to cdn0.scrvt.com for performance reasons.

Added link preconnect tag to cdn0.scrvt.com

---

src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetComponent.js

See https://www.ghacks.net/2018/05/23/why-you-should-always-use-youtubes-privacy-enhanced-mode/ for background

Use privacy enhanced YouTube embed

---

src/assets/stylesheets/_social_cards.scss

Scrivito 1.7.0 introduced progressive image loading.
For full compatibility, if the height of an `img` is set using CSS,
we should also specify a width.

Fix image aspect ratio in social cards tab

---

src/Components/BlogPost/BlogPostDate.js
src/Objs/Event/EventComponent.js
src/Objs/Job/JobComponent.js

It is now possible to edit dates of blog posts, jobs and events inplace:
Please note, that you still have to use the page properties for a blog post without a date.

Inplace edit dates

---

package-lock.json
package.json
src/App.js
src/Components/CurrentPageMetadata.js
src/Components/ErrorBoundary.js
src/Components/Intercom.js
src/Components/NotFoundErrorPage.js
src/Components/Tracking.js
src/prerenderContent/prerenderObj.js

Type declaration file of `react-helmet-async` still uses obsolete `react-helmet` - see: https://github.com/staylor/react-helmet-async/blob/master/index.d.ts#L3
That's why I didn't remove it from dependencies. Maybe is there any safe-circumvention?
The package `react-helmet` seems to be outdated and no longer maintained. There is a fork by the New York Times, that addresses most of the known issues (`react-helmet-async`). See https://open.nytimes.com/the-future-of-meta-tag-management-for-modern-react-development-ec26a7dc9183 for the background on the fork.

Introduce helmet-react-async

---

public/_redirects
src/Components/NotFoundErrorPage.js

This PR does two things:
* Do not redirect on the 404 page, if in the Scrivito UI.
* Use a query param (a.k.a. "search") instead of the path for the 404 status code indicator. Also leave all other parts of the URL as is.

404 bugfix

---

generator-scrivito/generators/obj/templates/XEditingConfig.js.ejs
src/Objs/Author/AuthorEditingConfig.js
src/Objs/Blog/BlogEditingConfig.js
src/Objs/BlogPost/BlogPostEditingConfig.js
src/Objs/Event/EventEditingConfig.js
src/Objs/Homepage/HomepageEditingConfig.js
src/Objs/Job/JobEditingConfig.js
src/Objs/LandingPage/LandingPageEditingConfig.js
src/Objs/Page/PageEditingConfig.js
src/Objs/SearchResults/SearchResultsEditingConfig.js
src/Objs/_defaultPageEditingConfig.js
src/Objs/_metadataEditingConfig.js

merge `socialCardsPropertiesGroup` and `metadataPropertiesGroup`into new `metadataPropertiesGroups`
merge `socialCardsValidations` in `metadataValidations` (preperation)
wrapped `defaultPageTitleValidation` in an array and renamed it to `defaultPageTitleValidations`
added `validations` to `XEditingConfig.js.ejs `

Refactoring: metadataPropertiesGroups

---

package.json
webpack.config.js

Otherwise `devServerCspHeaders` modifies `headersCsp` directly and adds `"'unsafe-eval'"` to `script-src`!

[webpack] Bugfix: Deep Clone headersCsp in devServerCspHeaders.

---

src/Objs/_metadataEditingConfig.js

After some discussion we decided to no longer recommend writing page descriptions.
Google is usually smart enough to pick up a reasonable description from the content of the page.

Discontinue page description validations.

---

package-lock.json
package.json

Updated Scrivito to 1.12.0.
See https://www.scrivito.com/scrivito-js-1-12-0-released-featuring-workflows-and-page-history-a2ee76c7cbe41945 for details about the release.

Scrivito 1.12.0

---

webpack.config.js

Motivation: This makes it easier for the content script to access `index-<some-hash>.js`.

[webpack] Compile asset-manifest.json in dev mode.

---

package-lock.json
package.json

```
Module build failed (from ../node_modules/babel-loader/lib/index.js):
Error: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- ~/scrivito_example_app_js/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
```
Solution found here:
https://github.com/storybookjs/storybook/issues/10477#issuecomment-619423402

Node > 12 compatibility

---

public/_headersCsp.json

This is the newer version of the deprecated "X-Frame-Options" header.
This PR also white-lists `https://*.scrivito.com` which will soon be a new place to edit scrivito content.

[csp] Added "frame-ancestors" policy.

---

src/Widgets/GoogleMapsWidget/GoogleMapsWidgetComponent.js
src/Widgets/VimeoVideoWidget/VimeoVideoWidgetComponent.js
src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetComponent.js

This allows to save the bandwidth, since the iframe is only loaded once being near the viewport. Browsers that do not support this feature simply ignore this attribute.
See https://web.dev/iframe-lazy-loading/ for more details.
This saves around ~500 KB on initial page load *per YouTube or Vimeo* widget. So having two of these widget on page page saves ~1000 KB.

Add 'loading="lazy"' to all iframes.

---

package-lock.json
package.json
src/Components/AnimateOnReveal.js

`react-reveal` is no longer maintained since two years. `react-reveal-iframe` has at least some small improvements to keep it alive.

react-reveal => react-reveal-iframe

---

package-lock.json
package.json

Version 6.0.1 and newer (including 6.1.0) do not process the "transform" option well. `CSP-DIRECTIVES-PLACEHOLDER` inside of `_headers` is not replaced well.
Broken since https://github.com/Scrivito/scrivito_example_app_js/pull/330.
I will update the PR once I created an issue on https://github.com/webpack-contrib/copy-webpack-plugin.

[npm] Bugfix: Downgraded "copy-webpack-plugin" to version 6.0.0 for now.

---

package-lock.json
package.json
webpack.config.js

Follow-up of https://github.com/Scrivito/scrivito_example_app_js/pull/339.
If multiple patterns reference similar or identical files (e.g. "../public" and "../public/_headers") it is not well defined, which pattern will be executed - the first or the last? ~To avoid this confusion now "../public" is copied, but only "public/_headers" is transformed.~ TO avoid this confusion copying `../public` does explicitly exclude `../public/_headers`.
copy-webpack-plugin 6.0.1 most likely broke because of https://github.com/webpack-contrib/copy-webpack-plugin/pull/484.

Make transform also work for copy-webpack-plugin 6.1.0.

---

package-lock.json
package.json
src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidget.scss
src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js
webpack.config.js

`ThumbnailGallery` previously used [`react-images`](https://www.npmjs.com/package/react-images). Now it uses [`react-bnb-gallery`](https://www.npmjs.com/package/react-bnb-gallery).
According to [`react-images`](https://www.npmjs.com/package/react-images)'s own readme:
> ⚠️  Warning!
>
> Don't use this in a new project. This package hasn't been properly maintained in a long time and there are much better options available.
So we needed a replacement.
Thankfully @pietruszka found a good library, that is quite an easy replacement: [`react-bnb-gallery`](https://www.npmjs.com/package/react-bnb-gallery). It works very similar to `react-images` and with a few tweaks looks at least similar.
To address filesize concerns about `react-bnb-gallery` we introduces code-splitting to cut of this part …

react-images => react-bnb-gallery + code splitting

---

package-lock.json
package.json

I did check the resulting css output. Besides some reordering and some minor arithmetic precision difference the output is identical.
The `sass` package is a distribution of [Dart Sass](https://github.com/sass/dart-sass), compiled to pure JavaScript with no native code or external dependencies.
> ### Why Dart?
> Dart Sass has replaced Ruby Sass as the canonical implementation of the Sass language. We chose Dart because it presented a number of advantages:
>
> * It's fast. The Dart VM is highly optimized, and getting faster all the time (for the latest performance numbers, see perf.md). It's much faster than Ruby, and close to par with C++.
> * ...
Source: https://github.com/sass/dart-sass#why-dart
The `node-sass` package is a wrapper around [LibSass](https://sass-lang.com/libsass), the …

node-sass => (dart-)sass

---

package-lock.json
package.json
src/Widgets/GoogleMapsWidget/GoogleMapsWidgetComponent.js

Follow-up to https://github.com/Scrivito/scrivito_example_app_js/pull/349#discussion_r515858241
https://www.npmjs.com/package/use-resize-observer#the-onresize-callback
> By the default the hook will trigger a re-render on all changes to the target element's width and / or height.
That's why we don't have to compare anymore an old and a new size.

Replace resize with hook

---

src/Objs/SearchResults/SearchResultsComponent.js

The error can be observed, if one calls "npm run prerender".
Introduced with https://github.com/Scrivito/scrivito_example_app_js/pull/352.

Bugfix: No longer crash SearchResultsComponent, if params.q is undefined

---

src/Objs/_defaultPageAttributes.js
src/Widgets/VideoWidget/VideoWidgetClass.js
src/config/index.js
src/config/objClassForContentType.js
src/config/scrivito.js

IF you upload a video to the Content Browser it now automatically becomes a "Video" obj class. Previously it was a generic "Download" obj class. See https://www.scrivito.com/js-sdk/configureObjClassForContentType for more details.
Because of that, we can restrict `VideoWidget` and `navigationBackgroundImage` more to `Video` or `Image`/`Video`.

Use configureObjClassForContentType

---

src/config/history.js
src/config/index.js
src/config/objClassForContentType.js
src/config/scrivito.js
src/config/scrivitoContentBrowser.js
src/config/windowScrivito.js
src/index.js
src/prerender_content.js
src/scrivito_extensions.js
webpack.config.js

The `priority` allows to differentiate between `foreground` and `background`. If set to `background` a different rate limit is used than with `foreground`. This should ensure, that prerendering tasks do not "eat" rate of visitors. See https://www.scrivito.com/js-sdk/configure for more details.
For this to work visitors must _not_ use `background` for the `priority`. Since https://github.com/Scrivito/scrivito_example_app_js/pull/366 that was sadly the case, if you prerendered the site.
This PR fixes the issue by only setting `background` during actual prerender (`src/prerender_content.js`) and _not_ during "regular" visits (`src/index.js`).
Diff best reviewed without whitespace changes.

Bugfix: Only use background priority during prerender.

---

src/config/scrivito.js

This is general best practice, but also handy when running the code under Node.js in conjunction with `dotenv`.

Make configureScrivito side-effect free

---

src/Components/CookieConsentContext.js
src/config/index.js
src/utils/fullScreenWidthPixels.js

Three smaller changes to be able to render server side, even without a `window`.
**Note**
I also considered moving `configureScrivitoContentBrowser()` and `configureObjClassForContentType()` to the window specific block. These are not strictly needed in a window-less (and thus no-editing) environment.

Better SSR support

---

package-lock.json
package.json

[Scrivito 1.22.0](https://www.scrivito.com/scrivito-js-1-22-0-released-featuring-language-aware-search-bc64a95b4cb84800) is out. This PR incorporates this version and also updates other npm packages.

Scrivito 1.22.0 (+ npm update)

---

src/index.js
src/prerenderContent/generatePreloadDump.js

Fixes a bug where a dump containing one of the line terminators `<LS>` and `<PS>` (see https://262.ecma-international.org/5.1/#sec-7.3) would lead to invalid code on older browsers (👋 IE11).
As an additional optimization, we allow to garbage collect the dump string after use.

Prerendering: Fix <LS> and <PS> line terminators for IE11

---

.travis.yml
netlify.toml

I already switch locally to npm 7 in [1]. But I did not yet switch to npm 7 on Travis and Netlify. Now is the time.
Without this change subtle failures could emerge. E.g. an update of webpack locally ran fine, but failed on Netlify.
This can be removed, as soon as the node version installs npm v7 by default. According to [2] this is node version 15 or newer.
Inspired by [3] and [4].
Please note, that you'll need to clear your Netlify cache. Otherwise your build will fail due to wrong npm package cache.
[1] https://github.com/Scrivito/scrivito_example_app_js/pull/375
[2] https://nodejs.org/en/download/releases/
[3] travis-ci/travis-ci#4653 (comment)
[4] https://docs.netlify.com/configure-builds/manage-dependencies/#npm

Use npm 7 on Travis and Netlify

---

package.json
webpack.config.js
webpack.config.production.js

We now have:
* `webpack.config.js` for the development setup. It is agnostic of a production setup. To keep the EnvironmentPlugin use DRY, it still looks at `env.production` once, but this is an official webpack env. Alternative ideas welcome.
* `webpack.config.production.js` for production. It relies on the dev setup to provide sensible defaults. The production settings are then added to the default, and filtered where needed.

Simplify webpack config by separating development and production

---

.eslintrc
package.json
webpack.config.js
webpack.config.production.js

With two small exceptions we can run eslint on webpack configs.

Run eslint on webpack configs

---

src/Components/CurrentPageMetadata.js

Falls back to "en" if no language is provided.

Make use of the page defined language as html lang attribute.

---

src/Objs/Homepage/HomepageEditingConfig.js
src/Objs/Homepage/HomepageObjClass.js

Since [version 1.22.0](https://www.scrivito.com/scrivito-js-1-22-0-released-featuring-language-aware-search-bc64a95b4cb84800) Scrivito provides a way for editors to set a title only for editors. To use it, one has to provide a `contentTitle` attribute of type `string`.
This PR adds `contentTitle` attribute to ~every non-binary obj class~ _Homepage_.

Added "Title for editors" to Homepage obj class.

---

webpack.config.js

Fixes #399 (webpack >=v5.24.1 compatibility)
according to https://github.com/webpack/webpack.js.org/issues/4837#issuecomment-816754861

Don't apply module concatenation twice

---

webpack.config.js

Introduced in 497c14646d1bc53db41c57d9103a175952b52641
`env` actually looks like `{ WEBPACK_BUNDLE: true, WEBPACK_BUILD: true, production: true }`

Fix refactoring oversight in EnvironmentPlugin

---

src/Objs/Homepage/HomepageEditingConfig.js

* Move to the top of the "Site settings" tab
* Improve the label according to an internal discussion
Follow-up to https://github.com/Scrivito/scrivito_example_app_js/pull/394#pullrequestreview-654382514

Make `contentTitle` for homepages more self-explanatory

---

src/Components/ScrivitoExtensions/ColumnsEditorTab.js
src/Components/ScrivitoExtensions/IconEditorTab.js
src/Components/ScrivitoExtensions/IconEditorTab/AllIcons.js
src/Components/ScrivitoExtensions/IconEditorTab/IconSearch.js
src/Components/ScrivitoExtensions/IconEditorTab/IconSearchResults.js
src/assets/stylesheets/_grid_layout_editor.scss

IconEditorTab and ColumnsEditorTab should both be be usable in a "read-only" mode.
This is checked using [`Scrivito.canWrite()`](https://www.scrivito.com/js-sdk/canWrite).
IconEditorTab was also converted to React Hooks.
Diff best viewed without whitespace changes.

Improved custom widget components

---

src/Components/CookieConsentContext.js
src/Objs/Homepage/HomepageEditingConfig.js

Google Chrome seems to treat direct access to "localStorage" in an iframe in incognito as a "third party cookie" and blocks it (see [1]).
[1] https://github.com/elastic/kibana/issues/87901#issuecomment-758457425

CookieConsent: Treat denied localStorage as "declined" cookie banner.

---

package-lock.json
package.json
webpack.config.js

Tiny patch. Updated webpack-dev-server to 4.0.0.
**Note**: two depreciation warnings appear (DEP_WEBPACK_DEV_SERVER_CONSTRUCTOR and DEP_WEBPACK_DEV_SERVER_LISTEN). I wasn't able to find a root case :/ Npm installs packages seamlessly and project runs as it should, so I guess it can be a "general" warning even, if we don't use it in the code

webpack-dev-server update to 4.0.0 version

---

src/Objs/Homepage/HomepageEditingConfig.js

Google Analytics 4 (see [1]) is currently not supported (IDs starting with "G-"). Previous version of Google Analytics continue to work (now called "Universal Analytics property, IDs starting with "UA-") (see [2]). 
[1] https://support.google.com/analytics/answer/10447272
[1] https://support.google.com/analytics/answer/10269537

Add a validation for googleAnalyticsTrackingId.

---

webpack.config.js

Previously css changes where only visible after a manual refresh of the page - quite annoying. Now css is automatically refreshed on save - similar to js.
It looks like, that this is actually an issue of "html-webpack-plugin" with "contenthash". See https://github.com/jantimon/html-webpack-plugin/issues/1638 . This is more a workaround than an actual fix.

[webpack] Fixed css auto-reload issue.

---

src/assets/stylesheets/index.scss

Overriding `.btn` unfortunately also overrides `.btn-sm` and `.btn-lg`.
Now we stick with the default Bootstrap button font size of 1rem,
which should equal 16px.

Don't override Bootstrap `btn-lg`/`btn-sm` font size

---

src/prerenderContent/filenameFromUrl.js

This reverts commit 4ba5561124ed7144fd42978b45822b6c661a8363.
We've learned that while the `index.html` filename schema is less prone
to clashes and is better suited for serving on S3, it has an unwanted
SEO impact on Netlify:
The canonical URLs of Scrivito _don't_ use a trailing slash.
Netlify implements the `index.html` schema _with_ a trailing slash.
Thus, requests to the canonical URL cause an unnecessary 301 on Netlify.
With this change, requests to the canonical URL are served as 200 OK.
Some background:
* https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash
* https://github.com/gatsbyjs/gatsby/discussions/27889#discussioncomment-254854

Make generated HTML files more Netlify/SEO friendly

---

src/Components/BlogPost/BlogPostNavigation.js
src/Components/BlogPost/BlogPostPreviewList.js

Previously the navigation did not work reliably, if one or more "publishedAt" had the exact same value (e.g. three blog posts all starting at the same day). Now this is fixed by also checking for "same date" entries.

Bugfix: BlogPostNavigation can handle same date blog posts

---

src/Components/ScrivitoExtensions/ColumnsEditorTab.js

Otherwise an `widget.update` will not trigger a render of e.g. `widget.get("alignment")`.

Bugfix: Connect ColumnsEditor.

---

package-lock.json
package.json
src/Components/ScrivitoExtensions/ColumnsEditorTab.js
src/Components/ScrivitoExtensions/IconEditorTab.js
src/Components/ScrivitoExtensions/SocialCardsTab.js
src/Objs/_metadataEditingConfig.js
src/Objs/editingConfigs.js
src/Objs/index.js
src/Widgets/ColumnContainerWidget/ColumnContainerWidgetEditingConfig.js
src/Widgets/FeaturePanelWidget/FeaturePanelWidgetEditingConfig.js
src/Widgets/IconWidget/IconWidgetEditingConfig.js
src/Widgets/editingConfigs.js
src/Widgets/index.js
src/index.js
src/scrivito_extensions.js

[Scrivito `1.29.0`](https://www.scrivito.com/scrivito-js-sdk-1-29-0-released-f7dab02769bdb921) enables to dynamically load editing config later on.

Scrivito 1.29.0 + dynamic editing config

---

package-lock.json
package.json

Use "overrides" to help npm version 8.3 and newer.
The "overrides" flag allows to make specific changes to (sub-)dependencies (see [1]). It is supported by npm 8.3 and newer (see [2]).
With this change after an "npm i" "npm audit" will print "found 0 vulnerabilities". Previously it printed "6 moderate severity vulnerabilities".
[1] https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides
[2] https://github.com/npm/cli/releases/tag/v8.3.0

npm overrides

---

package-lock.json
package.json

The sub-dependency @caporal/core has a pinned version of lodash, that contains two security warnings ([1] and [2]). caporal itself already upgraded the lodash version in its current master (see [3]), but a push to npm did not yet happen.
[1] https://github.com/advisories/GHSA-35jh-r3h4-6jhm
[2] https://github.com/advisories/GHSA-p6mc-m468-83gw
[3] https://github.com/mattallty/Caporal.js/pull/210

es-check 5 => 6

---

src/Components/ScrivitoExtensions/ContentProperty.js

Under some circumstances, changing the `className` of the in-place editable element may decrease usability.

Separate input and styling element

---

package-lock.json
package.json

This version finally replaces Caporal with Commander (see [1]). Without caporal there is also no longer the need to "override" specific lodash versions.
[1] https://github.com/yowainwright/es-check/pull/159

Update es-check to version 7

---

src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js

As a preparation for future PRs: This PR cleans up `ThumbnailGalleryWidget` by converting it over to react hooks.
Diff best viewed one commit at a time and without whitespace changes.

ThumbnailGalleryWidget: Refactor to hooks

---

src/Components/ErrorBoundary.js
src/Components/NotFoundErrorPage.js
src/index.js
src/utils/getMetadata.js

AFAICS "prerender.io" is now only a "contact us" feature by netlify (see [1]). Since Scrivito supports much better ways now on how to prerender your content we can simplify this code.
[1] https://docs.netlify.com/site-deploys/post-processing/prerendering/#external-services

👋 prerender.io

---

src/config/history.js

Logical OR assignment seems to be not well supported by the current tools.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment
Follow up of https://github.com/Scrivito/scrivito_example_app_js/pull/496. I assume that some package of #497 does handle Logical OR assignment differently.

Fix "npm run es-check" error.

---

src/App.js

wrong component order leads to error in older versions of [ErrorBoundary.js](https://github.com/Scrivito/scrivito_example_app_js/blob/907d43020c9a91f531cb8f242e5aa20ac406a673/src/Components/ErrorBoundary.js)
see discussion in https://infopark.slack.com/archives/C5LGN1D42/p1674119386473099

fix component order

---

package-lock.json
package.json
src/Widgets/HeadlineWidget/HeadlineWidgetComponent.js

kebabCase will try to covert camelCase to camel-case:
```js
_.kebabCase('fooBar');
// => 'foo-bar'
```
Source: https://lodash.com/docs/4.17.15#kebabCase
This can have undesirable effects, if one inputs "normal" text. E.g. 
```js
_.kebabCase("Mapping sites and URLs dynamically")
// => "mapping-sites-and-ur-ls-dynamically"
```
With this change the anchor now looks like this:
```js
// => "mapping-sites-and-urls-dynamically"
```

HeadlineWidget: Improved automatic anchors.

---

src/assets/stylesheets/_scrivito_extensions.scss
src/assets/stylesheets/_social_cards.scss

| before | after |
| -- | -- |
| <img width="296" alt="image" src="https://github.com/Scrivito/scrivito_example_app_js/assets/986170/49aea6cb-06c3-4068-a805-84b1e0333333"> |  <img width="272" alt="image" src="https://github.com/Scrivito/scrivito_example_app_js/assets/986170/b988dcc3-fc89-4811-8777-d6e9c2d426ad"> |
This lead to bad UX if the input contains words longer than the available width, which happens most frequently in sidebar editing. Chrome automatically uses this style for contenteditable. Now, all browsers behave the same.

Fix property text inputs on Firefox

---

src/Widgets/HeadlineWidget/HeadlineWidget.scss
src/Widgets/HeadlineWidget/HeadlineWidgetComponent.js
src/assets/stylesheets/_navigation.scss

Also fixes the scroll margin for other link targets (e.g. #mainContent).
Examples:
* https://deploy-preview-525--scrivito-example.netlify.app/#mainContent
* https://deploy-preview-525--scrivito-example.netlify.app/pricing#compare-all-features
* https://deploy-preview-525--scrivito-example.netlify.app/pages-and-widgets#form_text_input_widget_2fd9e8a7

Replace headline widget scroll margin workaround

---

src/Widgets/FormCheckboxWidget/FormCheckboxWidgetClass.js
src/Widgets/FormCheckboxWidget/FormCheckboxWidgetEditingConfig.js
webpack.config.js

Neoletter has introduced partial (beta) support for "subscription". To make this feature compatible with the example app "Form Builder," I've implemented the first change by introducing a new checkbox type "subscription". 
As the "subscription" feature is still in its development stage and not yet documented, it remains concealed for standard users. Following the approach taken during the initial stages of Form Builder, I have opted to hide the "subscription" functionality under a special environment variable. 
`ENABLE_NEOLETTER_FORM_BUILDER_SUBSCRIPTION_FEATURE`
This approach ensures that the feature is accessible for testing and refinement while remaining hidden from regular users until it is fully prepared for deployment.
This initial pull request sets the groundwork for the …

Neoletter || Form builder || Add subscription checkbox type 

---

src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js

Despite setting autoComplete to 'off' the fax field was auto-filled in Chrome and Brave browsers. I resolved the issue using the suggestion from [this gist](https://gist.github.com/niksumeiko/360164708c3b326bd1c8?permalink_comment_id=4405851#gistcomment-4405851).

Form Builder || fix honeypot by adding presentation role to the fax field

---

src/Components/ScrivitoExtensions/IconEditorTab/IconSearch.js

This will fix the [Object Object] bug caused when reseting the icon search in IconEditorTab component.

Bugfix on reseting the search for icons

---

package-lock.json
package.json

Make use of https://www.scrivito.com/scrivito-js-sdk-1-41-0-released-5bbcf193274689d5.

Scrivito 1.41.0

---

.eslintrc
webpack.config.js

Without this, `npm run eslint` fails with
```
✖ 3499 problems (3499 errors, 0 warnings)
```
The README doesn't mention `.env` with `SCRIVITO_TENANT` as a prerequisite for developing, so
I think `ESLint` should work out of the box.

Fix ESLint if SCRIVITO_TENANT is unset
