- src/Components/Navigation.js
- src/Widgets/ContactFormWidget/ContactFormWidgetClass.js
- src/Widgets/ContactFormWidget/ContactFormWidgetComponent.js
- src/Widgets/ContactFormWidget/ContactFormWidgetEditingConfig.js
- webpack.config.js
The code is inspired by the former SignUpFormWidget:
> ContactForm: Added transparent option.

- src/Components/ErrorBoundary.js
> Error page no longer talks about "connecting to our system".

- package-lock.json
- package.json
Otherwise sometimes "npm run build" could fail.
> Explicitly added "core-js".

- src/Components/AuthorImage.js
- src/Components/BlogPost/BlogPostAuthor.js
- src/Components/BlogPost/BlogPostPreviewList.js
- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
- src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js
- src/utils/isImage.js
Solves: https://infopark.slack.com/archives/C5LGN1D42/p1518015213000769
> images: filter images with empty blob

- src/assets/stylesheets/_grid_layout_editor.scss
- src/assets/stylesheets/_icon_editor.scss
- src/assets/stylesheets/_social_cards.scss
- src/assets/stylesheets/index.scss
> Reformated "*.scss" with https://prettier.io

- src/Objs/SearchResults/SearchResultItem.js
E.g. https://scrivito-example.netlify.com/search_results?q=to%28
> Fix searches with special regex chars

- src/Components/GoogleAnalytics.js
- src/Objs/Homepage/HomepageEditingConfig.js
Follow up to https://github.com/Scrivito/scrivito_example_app_js/pull/32.
> Better Google Analytics

- src/Components/GoogleAnalytics.js
- src/Components/Intercom.js
As a follow up to https://github.com/Scrivito/scrivito_example_app_js/pull/47 and some feedback I received from Andreas I cleaned up `GoogleAnalytics` and `Intercom` a bit.
> Code cleanup

- public/_headers
This makes it easier to keep track of changes (e.g. avoid duplicates)
> Sort CSP hosts by name

- src/assets/stylesheets/index.scss
Simply updates the comment at the top of the file to prevent confusion of Bootstrap version.
> Update stylesheet to reflect Bootsrap 4

- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
- src/assets/stylesheets/index.scss
https://trello.com/c/y9PZyuNJ/277-editing-of-testimonial-slider-click-to-add-a-testimonial-should-also-look-good-on-dark-background
Added extra class `edit-mode-link` for links in edit mode on dark background
> Added new style for links in edit mode on dark background

- src/Widgets/JobOverviewWidget/JobOverviewWidgetClass.js
- src/Widgets/JobOverviewWidget/JobOverviewWidgetComponent.js
- src/Widgets/JobOverviewWidget/JobOverviewWidgetEditingConfig.js
https://trello.com/c/RWm6kEgz/344-bugfix-joboverviewwidget-should-work-with-newer-attributes-locationlocality-etc
Changed `location` attribute for current attribute `locationLocality`.
> Updated location attribute in job overview widget

- webpack.config.js
https://trello.com/c/TVAd8pU7/335-add-chrome-41-as-babel-env-target
> Added chrome 41 to targets in webpack config

- src/Widgets/GoogleMapsWidget/GoogleMapsWidgetClass.js
- src/Widgets/GoogleMapsWidget/GoogleMapsWidgetComponent.js
- src/Widgets/GoogleMapsWidget/GoogleMapsWidgetEditingConfig.js
- src/assets/stylesheets/index.scss
https://trello.com/c/CU0s2Uot/326-googlemaps-stand-alone-mode
> Added interactive map to google maps widget

- src/Widgets/VimeoVideoWidget/VimeoVideoWidgetComponent.js
- src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetComponent.js
- src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetEditingConfig.js
- src/assets/stylesheets/index.scss
https://trello.com/c/igu2t2sm/362-replace-js-based-aspect-ratio-calculation-with-css-version
Deleted some js code that counting width and height, despite of it created some css classes to manage the size of iframe content.
> Ratio update, changed into css

- src/Widgets/GoogleMapsWidget/GoogleMapsWidgetClass.js
- src/Widgets/GoogleMapsWidget/GoogleMapsWidgetComponent.js
- src/Widgets/GoogleMapsWidget/GoogleMapsWidgetEditingConfig.js
- src/assets/stylesheets/index.scss
Added interactive map.
https://trello.com/c/CU0s2Uot/326-googlemaps-stand-alone-mode
> Added interactive google map into map widget

- public/index.html
- public/js_snippets_before_body_end.js
- public/js_snippets_head.js
https://trello.com/c/3yONqHWK/368-header-end-of-body-js-placeholder-file
Added empty js placeholders files to input js content.
> Added placeholders js files

- public/_headers
https://trello.com/c/h3eitIb1/374-additional-headers-so-that-securityheaderscom-is-happy
Added new headers:
`Feature-Policy`
`Referrer-Policy`
`X-Content-Type-Options`
`X-XSS-Protection`
`X-Frame-Options`
Result: https://securityheaders.com/?q=https%3A%2F%2Fsparkling-prune-scrivito-0728.scrivito.net%2F&followRedirects=on
> Extended headers

- src/Components/Footer.js
https://trello.com/c/8mKBIMrG/376-footer-notice-that-footer-starts-here
Added info before the footer, that it'll look the same on every page.
The notice was consulted with Andreas.
> Added 'before footer' notice

- src/Components/AuthorImage.js
- src/Components/BlogPost/BlogPostPreviewList.js
- src/Components/CookieConsent.js
- src/Components/Navigation/FullNavigation.js
- src/Components/Navigation/ScrollToNextSectionLink.js
- src/Objs/Blog/BlogComponent.js
- src/Objs/SearchResults/SearchResultItem.js
- src/Widgets/CarouselWidget/CarouselWidgetComponent.js
- src/Widgets/ColumnContainerWidget/ColumnContainerWidgetComponent.js
- src/Widgets/EventOverviewWidget/EventOverviewWidgetComponent.js
- src/Widgets/GalleryWidget/GalleryWidgetComponent.js
- src/Widgets/IconContainerWidget/IconContainerWidgetComponent.js
- src/Widgets/JobOverviewWidget/JobOverviewWidgetComponent.js
- src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidgetComponent.js
- src/Widgets/VimeoVideoWidget/VimeoVideoWidgetComponent.js
- src/Widgets/YoutubeVideoWidget/YoutubeVideoWidgetComponent.js
https://trello.com/c/V59DFi9E/386-maintenance-consolidate-react-props-centertrue-into-center
Deleted all assignments true to true values.
> True is clear

- package-lock.json
- package.json
https://trello.com/c/HtKiEwEx/387-npm-update-including-latest-react
Updated:
`react`
`react-dom`
`webpack`
`webpack-dev-server`
> Npm update (including latest react)

- package-lock.json
- webpack.config.js
Trello: https://trello.com/c/0oxgXd8U/350-make-csp-work-in-development-mode
> Enable CSP during local development.

- generator-scrivito/app/index.js
- generator-scrivito/generators/obj/index.js
- generator-scrivito/generators/widget/index.js
Andreas suggested shorter messages for yeoman generator.
**Suggestions:** 
`Welcome to the Scrivito Obj/Widget generator!`
`? What do you want to generate?`
` An Obj class `
`❯ A Widget class`
`Welcome to the Scrivito Obj/Widget generator!`
`? What do you want to generate? A Widget class`
`? Enter the name of the new Widget class (e.g. GiphyWidget):`
`? Enter the name of the new Obj class (...):`
> Yeoman generator refactoring messages

- package-lock.json
- package.json
Also **updated**: 
`@babel/core` 
`@babel/preset-env`
> Npm update (including scrivito 1.4.0)

- public/robots.txt
Motivation: Lighthouse has one more reason less to complain.
Previous complaint: "robots.txt is not valid"
> Added very basic robots.txt

- public/_scrivito_extensions.html
- public/catch_all_index.html
(as nobody is changing this title tags in static HTML anyway, we don't see "Example App" anymore in production but something more meaningful)
> Changed title tag to something more generic string

- storePrerenderedContent.js
See https://stackoverflow.com/a/37592669
> Exit safely, without risk of log truncation

- src/prerenderContent/prerenderObjs.js
Otherwise memory consumption will always go up, until prerender is done.
If the memory consumption is still too high, try reducing the number of parallel prerenders from 10 to 5 objs.
> prerenderObjs: Only prerender up to 10 objs in parallel.

- storePrerenderedContent.js
Well, it's a typo in all minus one cases 😸
> Fix small typo

- package.json
- prerender/extendRedirects.js
Previously it allowed one warning.
> Fix "npm run eslint"

- src/index.js
- src/prerenderContent/prerenderObj.js
Motivation: less flicker during "reanimate".
Makes use of the newly added `Scrivito.isEditorLoggedIn()`.
> [js] Use ReactDOMServer.renderToString and ReactDOM.hydrate.

- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
- src/Widgets/TestimonialSliderWidget/testimonialSliderWidget.scss
- src/assets/stylesheets/index.scss
> chunked testimonialSliderWidget styles

- package-lock.json
- package.json
The current version is not working properly.
> Downgrade "react-cookie-consent".

- package-lock.json
- package.json
- src/Components/CookieConsent.js
Update react-cookie-consent 2.3.2 > 2.5.0
add css class for fixed position
> Update react-cookie-consent 2.3.2 > 2.5.0

- src/Widgets/GoogleMapsWidget/GoogleMapsWidget.scss
- src/assets/stylesheets/index.scss
Additionaly I removed `.margin-neg-offset` because I couldn't find it used anywhere neither
> Removed unused styles

- package-lock.json
- package.json
- src/index.js
The update of `eslint-plugin-prettier` is unrelated to the Scrivito update.
> Scrivito 1.9.0 + Scrivito.updateContent()

- src/Widgets/VimeoVideoWidget/VimeoVideoWidgetComponent.js
See https://vimeo.zendesk.com/hc/en-us/articles/360001494447-Using-Player-Parameters
> Privacy: do not track for Vimeo

- src/assets/stylesheets/_blog.scss
> BlogPostPreviewList: Fix order of blog post items.

- src/Components/BlogPost/BlogPostPreviewList.js
- src/assets/stylesheets/_blog.scss
> markup update for blog-timeline--divider

- src/assets/stylesheets/index.scss
@apepper  Needs less space on smaller screens.
> Cookie Banner mobile adaption

- .eslintrc
- src/Components/ScrivitoExtensions/SocialCardsTab.js
- src/Objs/Author/AuthorEditingConfig.js
- src/Objs/Blog/BlogEditingConfig.js
- src/Objs/BlogPost/BlogPostEditingConfig.js
- src/Objs/Event/EventEditingConfig.js
- src/Objs/Homepage/HomepageEditingConfig.js
- src/Objs/Job/JobEditingConfig.js
- src/Objs/LandingPage/LandingPageEditingConfig.js
- src/Objs/Page/PageEditingConfig.js
- src/Objs/SearchResults/SearchResultsEditingConfig.js
- src/Objs/_metadataEditingConfig.js
- src/assets/stylesheets/_social_cards.scss
Implements validations for the social cards tab for all page types, including styling for inplace validation messages.
Also increased limit for twitter description field to 200 characters.
> Validations for social cards

- .eslintrc
- src/Objs/Author/AuthorEditingConfig.js
- src/Objs/BlogPost/BlogPostEditingConfig.js
- src/Objs/Event/EventEditingConfig.js
- src/Objs/Homepage/HomepageEditingConfig.js
- src/Objs/Job/JobEditingConfig.js
- src/Objs/LandingPage/LandingPageEditingConfig.js
- src/Objs/Page/PageEditingConfig.js
- src/Objs/Redirect/RedirectEditingConfig.js
- src/Objs/SearchResults/SearchResultsEditingConfig.js
- src/Objs/_defaultPageEditingConfig.js
Adds validations to objs/pages.
See also [google doc](https://docs.google.com/document/d/1_Z1BfcyTo4FBuvIe6FLxTYQM_qgq6opD7nR0804IGiY/edit?ts=5dde8dc0#heading=h.q1nxq338ckww).
> Implements validations for objs/pages

- readme.mdown
Added a section that promotes the page/widget class generator.
> Readme: Added Generator Section

- src/Objs/_metadataEditingConfig.js
Added validations for metadata page description.
> Validations for page description

- src/Components/ErrorBoundary.js
- src/Components/NotFoundErrorPage.js
- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
Thank you unsplash for sharing such wonderful images to the world and also for providing the servers to download from!
We are simply switching over to our servers, since we do control them and no cookies are set while accessing those images.
> Replace unsplash URLs with our URLs.

- webpack.config.js
Follow up of https://github.com/Scrivito/scrivito_example_app_js/pull/285#issuecomment-588315838.
> [webpack] Automatically add SCRIVITO_ENDPOINT to CSP's "script-src".

- src/assets/stylesheets/bootstrap/bootstrap.scss
Broken since https://github.com/Scrivito/scrivito_example_app_js/pull/289.
> [css] Bugfix: Search input on mobile now looks good again.

- package-lock.json
- package.json
- src/_prerender_content.html
- src/_scrivito_extensions.html
- src/catch_all_index.html
- src/scrivito_extensions.js
- webpack.config.js
> **BREAKING CHANGES**
> The assets object which is used for the template parameters and inside hooks was changed. The chunks property was removed and the js and css property was converted from a string into an object `{ entryName: string, path: string}`
Source: https://github.com/jantimon/html-webpack-plugin/blob/master/CHANGELOG.md#400-2020-03-23
> html-webpack-plugin 3 => 4

- src/Widgets/ContactFormWidget/ContactFormWidget.scss
FIX https://github.com/Scrivito/scrivito_example_app_js/issues/302
> z-index fix for floating labels

- src/Components/SchemaDotOrg/dataFromBlog.js
> Remove incorrect space in blog schema context url

- src/Widgets/ThumbnailGalleryWidget/ThumbnailGalleryWidget.scss
- src/assets/stylesheets/_blog.scss
- src/assets/stylesheets/_navigation.scss
Fixes #317.
Just for references:
`cat _responsive.scss`:
```scss
/* - BS3 variables - */
$screen-xs-max: 767px;
$screen-sm-min: 768px;
$screen-sm-max: 991px;
$screen-md-min: 992px;
$screen-md-max: 1199px;
$screen-lg-min: 1200px;
```
> [css] Corrected breakpoints for Navigation, Blog and ThumbnailGalleryWidget

- package-lock.json
- package.json
See https://www.scrivito.com/scrivito-js-1-15-0-released-featuring-dates-of-first-and-most-recent-publish-4f277ce06c513361 for all the new features.
> Scrivito 1.15.0

- generator-scrivito/app/index.js
- generator-scrivito/generators/obj/index.js
- generator-scrivito/generators/widget/index.js
Inspired by https://github.com/Scrivito/scrivito_example_app_js/pull/345.
> "yo scrivito:obj [<name>]" and "yo scrivito:widget [<name>]"

- src/Widgets/ColumnWidget/ColumnWidgetEditingConfig.js
since it will only be created via a custom editor.
> Hide ColumnWidget from selection dialog

- src/Objs/SearchResults/SearchResultsComponent.js
> Bugfix: Trim input on SearchResults page.

- package-lock.json
- package.json
See https://www.scrivito.com/scrivito-js-1-18-0-released-featuring-the-widget-sidebar-fd4d3d6b56eee586 for all the new features.
> [npm] Update scrivito to 1.18.0

- prerender/storePrerenderedContent.js
Original patch by https://github.com/cbou (closes #363).
> Errors during prerender stop script

- src/Widgets/GroupWidget/GroupWidgetClass.js
- src/Widgets/GroupWidget/GroupWidgetComponent.js
- src/Widgets/GroupWidget/GroupWidgetEditingConfig.js
- src/assets/images/group_widget.svg
It is a simple div container that can hold multiple widgets.
> Added GroupWidget

- LICENSE
- src/_scrivito_extensions.html
- src/catch_all_index.html
- src/prerenderContent/generateHtml.js
> "Infopark Group GmbH" => "JustRelate Group GmbH"

- generator-scrivito/package-lock.json
- generator-scrivito/package.json
- package-lock.json
https://github.com/jonschlinkert/paged-request/pull/3 is now resolved and a new version has been released. No need to artificially limit the version of "yeoman-environment" in use.
> No explicit yeoman environment

- package-lock.json
- package.json
See [Scrivito 1.21.0 Release Notes](https://www.scrivito.com/scrivito-js-1-21-0-released-featuring-the-changes-sidebar-d08dc7db42e29336) for all details.
> npm i scrivito@latest (1.21.0)

- src/index.js
From https://reactjs.org/docs/react-dom.html#render :
> If the optional callback is provided, it will be executed after the component is rendered or updated.
> ReactDOM.render: Make use of official render callback.

- generator-scrivito/generators/obj/index.js
- generator-scrivito/generators/widget/index.js
- generator-scrivito/package-lock.json
- generator-scrivito/package.json
- package-lock.json
See https://github.com/yeoman/generator/releases/tag/v5.0.0 for breaking changes.
Version 3 had some npm security warnings.
> [generator-scrivito] Upgrade yo version from 3 to 5.

- src/Widgets/EventOverviewWidget/EventOverviewWidgetComponent.js
- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
Discovered while trying out TypeScript.
> Call function instead of just referencing it.

- package-lock.json
- package.json
- src/Objs/Homepage/HomepageEditingConfig.js
- src/Objs/Homepage/HomepageObjClass.js
- src/Objs/SearchResults/SearchResultsComponent.js
- src/Widgets/JobOverviewWidget/JobOverviewWidgetComponent.js
- src/config/scrivito.js
Release notes: https://www.scrivito.com/scrivito-js-sdk-1-24-0-released-featuring-further-performance-improvements-0f4bba50126bd54b
> Update to Scrivito 1.24.0

- package-lock.json
- package.json
> Update webpack-dev-server to v 4.1.0

- src/config/scrivito.js
This is available since 1.24.0.
I think that all Example App code is compatible with this setting.
> Enable optimized widget loading

- src/Components/ScrivitoExtensions/SocialCardsTab.js
- src/assets/stylesheets/_social_cards.scss
@apepper small fixes for https://github.com/Scrivito/scrivito_example_app_js/pull/428#discussion_r742330193
> Scrivito dark

- src/Widgets/ButtonWidget/ButtonWidgetClass.js
- src/Widgets/ButtonWidget/ButtonWidgetComponent.js
- src/Widgets/ButtonWidget/ButtonWidgetEditingConfig.js
This PR adds a fourth "alignment": "Block level"
> ButtonWidget: block alignment

- package-lock.json
- package.json
- src/Objs/_defaultPageEditingConfig.js
- src/Widgets/SectionWidget/SectionWidgetEditingConfig.js
https://www.scrivito.com/scrivito-js-sdk-1-27-0-released-7893c3a877e617f8
> Scrivito 1.27.0 + enabled attributes

- package-lock.json
- package.json
https://www.scrivito.com/scrivito-js-sdk-1-27-1-bugfix-release-fa50a6d54cc5ffbc
> Scrivito 1.27.1 + webpack updates

- package-lock.json
- package.json
- src/config/scrivito.js
See https://www.scrivito.com/scrivito-js-sdk-1-28-0-released-afb331f99b4dee3d for all the details.
> Scrivito 1.28.0

- package-lock.json
Update w3c-xmlhttprequest subdependency to fix https://github.com/ykzts/node-xmlhttprequest/issues/426
> Avoid issue in node

- package-lock.json
> npm rm generator-scrivito && npm i file:generator-scrivito
This should remove some security warnings.
> Reinstalled generator-scrivito

- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidget.scss
- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
Prevents "Links are not crawlable" reports by Lighthouse.
> TestimonialSliderWidget: Replaced empty a tag with button tag

- src/Components/Icon.js
- src/Components/Navigation/ScrollToNextSectionLink.js
- src/Components/Navigation/Search.js
- src/Widgets/DividerWidget/DividerWidgetComponent.js
- src/Widgets/GalleryWidget/GalleryWidgetComponent.js
- src/Widgets/TestimonialSliderWidget/TestimonialSliderWidgetComponent.js
Follow up of https://github.com/Scrivito/scrivito_example_app_js/pull/466.
> Improve accessibility

- generator-scrivito/generators/obj/templates/XObjClass.js.ejs
- generator-scrivito/generators/widget/templates/XWidgetClass.js.ejs
Follow up of https://github.com/Scrivito/scrivito_example_app_js/pull/484.
> [generator-scrivito] Generate new Objs/Widgets with named exports.

- src/Objs/SearchResults/SearchResultsComponent.js
- src/Widgets/CarouselWidget/CarouselWidgetComponent.js
- src/Widgets/EventOverviewWidget/EventOverviewWidgetComponent.js
- src/Widgets/JobOverviewWidget/JobOverviewWidgetComponent.js
- src/Widgets/TableWidget/TableWidgetComponent.js
At least `CarouselWidgetComponent.js` contained a bug, that printed a warning for adding the same image multiple times. This bug got fixed in this PR.
> Improved key attributes

- src/Widgets/FormContainerWidget/FormContainerWidget.scss
- src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
This is the continuation of: https://github.com/apepper/scrivito_example_app_js/pull/29
> FormContainerWidget - implement honeypot fax field

- src/Widgets/FormButtonWidget/FormButtonWidgetClass.js
- src/Widgets/FormButtonWidget/FormButtonWidgetComponent.js
- src/Widgets/FormButtonWidget/FormButtonWidgetEditingConfig.js
- src/Widgets/FormCheckboxWidget/FormCheckboxWidgetClass.js
- src/Widgets/FormCheckboxWidget/FormCheckboxWidgetComponent.js
- src/Widgets/FormCheckboxWidget/FormCheckboxWidgetEditingConfig.js
- src/Widgets/FormContainerWidget/FormContainerWidgetClass.js
- src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
- src/Widgets/FormContainerWidget/FormContainerWidgetEditingConfig.js
- src/Widgets/FormHiddenFieldWidget/FormHiddenFieldWidgetClass.js
- src/Widgets/FormHiddenFieldWidget/FormHiddenFieldWidgetEditingConfig.js
- src/Widgets/FormInputFieldWidget/FormInputFieldWidgetClass.js
- src/Widgets/FormInputFieldWidget/FormInputFieldWidgetComponent.js
- src/Widgets/FormInputFieldWidget/FormInputFieldWidgetEditingConfig.js
- webpack.config.js
Neoletter can now handle every scrivito tenant.
Diff best viewed without whitespace changes.
The existing `ContactFormWidget` needs to be dealt with in a different PRs.
> RIP process.env.ENABLE_NEOLETTER_FORM_BUILDER

- package-lock.json
- package.json
See https://www.scrivito.com/scrivito-js-sdk-1-32-0-released-6dc70e6597de3661 for all the greatness of the release.
> Scrivito 1.32.0

- package-lock.json
- package.json
- public/_headersCsp.json
- public/js_snippets_head.js
- src/Components/Tracking.js
- src/Objs/Homepage/HomepageEditingConfig.js
- src/Objs/Homepage/HomepageObjClass.js
- src/tracking.js
"Universal Analytics" will soon be dysfunctional (see [1]). Cookie consent and `src/tracking.js` are still there, so that people can easily add their tracking code.
[1] https://support.google.com/analytics/answer/11583528
> Removed "Universal Analytics" Google Analytics

- src/Widgets/FormContainerWidget/FormContainerWidgetComponent.js
- src/Widgets/FormHiddenFieldWidget/FormHiddenFieldWidgetComponent.js
- src/Widgets/FormHiddenFieldWidget/FormHiddenFieldWidgetEditingConfig.js
> Bugfix: Render hidden fields as a dedicated component

- src/Widgets/FormButtonWidget/FormButtonWidgetComponent.js
Improvement for once Scrivito 1.34 (with https://github.com/infopark/scrivito_js/issues/9322) has been released.
> Make FormButtonWidget in-place editable

- package-lock.json
- package.json
See https://www.scrivito.com/scrivito-js-sdk-1-36-0-released-eb8cfd256336ed0e for more details.
> Scrivito 1.36.0

- src/Widgets/FormCheckboxWidget/FormCheckboxWidgetComponent.js
- src/Widgets/FormInputFieldWidget/FormInputFieldWidgetComponent.js
The removed code was a workaround for a Scrivito in-place editing issue fixed in 1.34.0.
> Simplify htmlFor

- src/Objs/_metadataEditingConfig.js
See https://github.com/Scrivito/scrivito-portal-app/pull/461#discussion_r1647188206
> Add missing social cards tab properties

- src/Components/AuthorImage.js
- src/Components/Navigation.js
More a formal removal than anything actually reasonable. Due diligence ftw 🙈.
> Unlink stack overflow answers
